### ISSUE TITLE
Drupal installation instructions

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#12]
Hello,

does it make sense to include some instructions on how to add the CKEditor Plugin to Drupal? It seems to me that the process is only slightly bigger, as it also involves changing a couple of lines of code in the [CKEditor Drupal module](https://www.drupal.org/project/ckeditor) configuration file and then activating the plugin from the Administration Panel. Can you confirm this? Of course, I can help with the instructions once I get the installation right.

**Comment by pheyvaer** [comment]
Yes, sure, from our side we haven't tried it with Drupal yet. However, if you can provide us with the instructions that would be great.

**Comment by jnehring** [comment]
@Katsivelisp any news on the instructions?

**Comment by Katsivelisp** [comment]
@jnehring @pheyvaer I just submitted a pull request with the proposed changes.

**Comment by bjdmeest** [comment]
Merged #16
