### ISSUE TITLE
Error 400: Bad request in Chrome with entity linking

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#17]
Hi, 

revisiting [this link](http://waterpathogens.agroknow.gr/node/add/test) with Chrome, I try to perform Entity Linking with DBpedia, but I get Error 400: Bad request in console. The invoked URL is the following:
[http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all&%3Cp%3EThe%20Polyomaviruses%20are%20prevalent%20in%20global%20populations%2C%20known%20to%20cause%20serious%20illness%20in%20immunocompromised%20individuals%20and%20are%20found%20at%20fairly%20high%20levels%20in%20sewage.%26nbsp%3B%20While%20our%20knowledge%20base%20is%20growing%20their%20importance%20in%20sewage%20is%20just%20now%20being%20recognized%20as%20source%20tracking%20markers%20and%20potential%20waterborne%20pathogens.%3C/p%3E](http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all&%3Cp%3EThe%20Polyomaviruses%20are%20prevalent%20in%20global%20populations%2C%20known%20to%20cause%20serious%20illness%20in%20immunocompromised%20individuals%20and%20are%20found%20at%20fairly%20high%20levels%20in%20sewage.%26nbsp%3B%20While%20our%20knowledge%20base%20is%20growing%20their%20importance%20in%20sewage%20is%20just%20now%20being%20recognized%20as%20source%20tracking%20markers%20and%20potential%20waterborne%20pathogens.%3C/p%3E)

**Comment by Katsivelisp** [comment]
It seems to me that this issue is fixed once you add the parameter "&input=" before the text in the URL. Can you verify this?

**Comment by bjdmeest** [comment]
Very strange.. I issue a POST request, with as body the content (which is also why I don't need to URIencode is, so related to #18 ), but it gets translated to a GET request on your installation (and thus the 400). I have updated all links (back) to point to the 0.6 stable FREME APIs, and everything seems to work on http://api-dev.freme-project.eu/ckeditor/ckeditor/samples/freme.html. Could you update and see whether this and #18 is resolved?

I issue a POST request instead of a GET request, because it is not possible to support the linking of pretty large texts when using GET parameters.

**Comment by Katsivelisp** [comment]
I changed it, but it doesn't seem to have any difference.

**Comment by Katsivelisp** [comment]
I think I got it, if you don't specify the "type" ('POST') parameter in the $.ajax call, it defaults to 'GET'. So just change doRequest() to this:
```
    function doRequest(method, url, data, headers, success, error) {
        $.ajax({
                method: method,
                headers: headers,
                data: data,
                type: 'POST',
                url: url
            })
            .done(success)
            .fail(error);
    }
```

**Comment by bjdmeest** [comment]
Aha, I see you are using jQuery 1.7.1 instead of >=1.9, which is why it
doesn't work for you. I will make this change, but as I only test on jQuery
>= 1.9, other problems might arise for you

2016-06-30 16:09 GMT+02:00 Katsivelisp <notifications@github.com>:

**Comment by Katsivelisp** [comment]
Yeah, I changed it temporarily. It is 1.10 now.
