### ISSUE TITLE
Entity linking with text containing URL-reserved characters

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#18]
Hi,

it seems to me that Entity Linking does not work properly when the given text contains URL-reserved characters, like "%" or "&". Is it possible that the CKEditor plugin performs URL encoding to the source text before invoking the FREME services? I can provide you with an example later on.

**Comment by bjdmeest** [comment]
Can this be closed based on fd136ee?

**Comment by Katsivelisp** [comment]
Yes, agreed.
