### ISSUE TITLE
Error 406 (Not Acceptable): Linking Error

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#19]
Hi again,

I'm trying to perform entity linking on [this instance](http://waterpathogens.agroknow.gr/node/1535/edit) ("Body" field) and the invoked URL doesn't seem to include the source text, thus resulting in Error 406. Any ideas on what might be wrong? 

Edit: By the way, if you just keep the first sentence, the linking seems to be running, but with some "irregularities".

**Comment by bjdmeest** [comment]
Could you update the ckeditor plugin and re-check? There are some
api-changes in the dev-version, which results in the 406. As the updated
ckeditor plugin uses the 0.6 stable, this should not be a problem.

2016-06-30 16:45 GMT+02:00 Katsivelisp <notifications@github.com>:

**Comment by Katsivelisp** [comment]
I see. I pulled the latest changes. I also forgot we have to load our custom dataset on the live API as well :) . Once this is done, I'll re-check.

**Comment by Katsivelisp** [comment]
It all works great, we just tried the plugin with a huge scientific text and linking was done seamlessly! Great work guys and thank you very much! :)
