### ISSUE TITLE
Datasets should be configurable

### ISSUE THREAD

**Issue by bjdmeest** [freme-project/CKEditor-Plugin#20]

**Comment by bjdmeest** [comment]
And languages for the different services too

**Comment by bjdmeest** [comment]
solved by eee46a4aa5c8f4f82adaaf42ef1a03999157da9d

**Comment by Katsivelisp** [comment]
Very helpful, thanks! :)

**Comment by Katsivelisp** [comment]
@bjmeest, I think it makes sense that this should be pushed to the main branch as well.

**Comment by bjdmeest** [comment]
done! :) (15697f5558cd384fdfda8bce4d4d6a4a10ecaebf)
