### ISSUE TITLE
Changing the HTML element of the linked entities from <span> to <a>

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#22]
Follow-up of the discussion started, I understand that the FREME output produces these <span> elements and we will have to invoke FREME NER with a certain template. Is this correct? How can we proceed exactly?

**Comment by bjdmeest** [comment]
I would suggest keeping this more specific to the plugin: call the FREME service as is, and visualize as we please. Of course, the more complex the visualization, the more complex if gets. My current suggestion would have some kind of configuration in the ckeditor-editor, where you can add additional markup, e.g.:

```
{
'class': '' // do not add additional markup if only the class is identified
'identifier': '<a href="$identifier">$text</a>' // add a link to the identified URI, if that is identified
}
```

**Comment by Katsivelisp** [comment]
I'm not sure I understand what you mean, probably because I'm relatively new to CKEditor. Is this some kind of markup that I can add to CKEditor and match occurrences of <span> elements on submit?

**Comment by bjdmeest** [comment]
I meant some extra configuration I could add to the freme-plugin, to specify what markup should be added to detected entities (such as, e.g., the link element)

**Comment by Katsivelisp** [comment]
This sounds ideal. Thank you. How soon can you do this? We can help if needed, of course.

**Comment by bjdmeest** [comment]
Looking into this as we speak, getting back to you before monday-noon :)

**Comment by bjdmeest** [comment]
Please see d5d220912726fc4ffdd8d3952284530326b80c4e , I took the liberty to also merge with the ak branch and update the config to your use case. Could you check and close this issue if this is ok?

**Comment by Katsivelisp** [comment]
It works like a charm. Templates are very convenient. Thank you very much for your support, @bjdmeest!  :)

**Comment by Katsivelisp** [comment]
@bjdmeest, @fsasaki proposed that this could also be pushed to the main branch, as it is a valid generic feature.

**Comment by bjdmeest** [comment]
Well, I was planning on updating the master branch, and by just doing so (15697f5558cd384fdfda8bce4d4d6a4a10ecaebf), this is added to the master branch :)

**Comment by fsasaki** [comment]
Great, thanks :)
