### ISSUE TITLE
plugin points to old FREME version

### ISSUE THREAD

**Issue by fsasaki** [freme-project/CKEditor-Plugin#26]
See
https://github.com/freme-project/CKEditor-Plugin/search?utf8=%E2%9C%93&q=api&type=Code

some parts of the plugin still point to FRMEE 0.6 which is not running anymore. One may want to replace this with e.g.

>http://api.freme-project.eu/current/

**Comment by bjdmeest** [comment]
The problem with /current/ is that the templates will break when a new
version is released. It's just a matter of re-executing
`createTemplates.js` and updating the template-ids, so no big deal, someone
just needs to do it when a new version is released (and using the version
numbers makes this a bit more manageable).

It however seems that no releases are online on 0.6, 0.7, ... So I'll
change to /current/

2016-09-19 8:18 GMT+02:00 Pieter Heyvaert <notifications@github.com>:

**Comment by bjdmeest** [comment]
fixed by 0a8505d264eba7a2db1cd2bb44d9e61c919b327f
