### ISSUE TITLE
adding e-terminology support to ck editor

### ISSUE THREAD

**Issue by fsasaki** [freme-project/CKEditor-Plugin#29]
The topic has been discussed between agro-know @Katsivelisp and others. I tried to implement this in my local installation of the ck editor and it worked easily (though I just replaced the e-entity functionality, so the real implementation of this is better be done by @bjdmeest  ).

One potential issue: ck editor uses e-internationalisation, and in this way e-terminology output looks e.g. like this:

>  &ltspan its-term="yes“ its-term-info-ref="http://freme-project.eu/#char=0,9">some term&lt;/span>

That is, term-info-ref does not contain a reference to the entry in the term data base but to the identifier for the annotation. For the rationale on this, see https://github.com/freme-project/basic-services/issues/56#issue-164661021

This could create issues for ck editor, since the user probably expects the reference to the term data base entry. Putting @philinthecloud and @katia-vistatec and @borriellom into the loop, they may be able to help to resolve this.

**Comment by fsasaki** [comment]
@bjdmeest , any news on this?  @philinthecloud and @katia-vistatec and @borriellom, would you be able to adapt the e-internationalisation output for e-terminology again, or should ck editor do two calls to FREME, one with output html, one with output e.g. json-ld (using e.g. a sparql output filter), and then traverse the json-ld to get the terminology related information?

**Comment by bjdmeest** [comment]
A first version (workflow as suggested by @fsasaki ) is online at https://api-dev.freme-project.eu/ckeditor-dev/ckeditor/samples/freme.html, by commit a966787b1edfe39eb13c1a4f7560e0ac98f3f57d . Feel free to comment or approve :).

Some current flaws:
* only the first term reference is used, even if a term has multiple detections, see below (I currently have no idea which one would be the 'best', so I just pick the first)
* combination with e-entity is flaky and currently not recommended
* due to the dual calls (once for HTML, once for JSON), the detection takes a while

```
{
      "@id": "http://freme-project.eu/#char=110,114",
      "@type": "nif:RFC5147String",
      "anchorOf": {
        "@language": "en",
        "@value": "lied"
      },
      "annotationUnit": "_:b6",
      "beginIndex": "110",
      "endIndex": "114",
      "referenceContext": "http://freme-project.eu/#char=0,470",
      "term": "yes",
      "termInfoRef": [
        ":4724932",
        ":1529587",
        ":1153642"
      ]
    }
-->
<a href="https://term.tilde.com/terms/4724932">[...]</a>
```

**Comment by Katsivelisp** [comment]
Hello @bjdmeest and thank you for your work! 

Just a question: If we want to perform term detection against a custom collection uploaded to Tilde, we have to do minor changes in the plugin code, right?

**Comment by bjdmeest** [comment]
Yes, didn't do that yet, I wasn't sure it was needed, so at the moment, you would have to change https://github.com/freme-project/CKEditor-Plugin/blob/dev/ckeditor/plugins/freme/dialogs/terminology.js#L13 and https://github.com/freme-project/CKEditor-Plugin/blob/dev/ckeditor/plugins/freme/dialogs/terminology.js#L34 . I will look into whether it's possible to do this via a dropdown in the ckeditor dialog though, that seems more user-friendly ;)

**Comment by bjdmeest** [comment]
I didn't find a way to retrieve the list of available collections, so I just added a text input field via 72c6d50a07fdc01c8bb180ae67dd1cd3be3df19a :). online at https://api-dev.freme-project.eu/ckeditor-dev/ckeditor/samples/freme.html

**Comment by fsasaki** [comment]
A suggestion: have instead of

> &lt;a href="https://term.tilde.com/terms/1503581" its-term-info-ref="http://freme-project.eu/#char=1,8">Chinese &lt;/a>

the following 

> &lt;a data-term-info-refs="https://term.tilde.com/terms/someTermId https://term.tilde.com/terms/anotherTermId" its-term-info-ref="https://term.tilde.com/terms/1503581">Chinese &lt;/a>

this would mean two changes: 1) use term-info-ref instead of href to store the term reference. I know that the e-internationalisation output contains the anchor URI like http://freme-project.eu/#char=1,8 . but this is from my understanding not useful for an application. 2) @bjdmeest  rightly pointed out that there may be several term references. In that case one could use the data-term-info-refs attribute to store these references, and then one of them in term-info-ref. The same approach is used for e-entity.

**Comment by katia-vistatec** [comment]
I remember ( see https://github.com/freme-project/basic-services/issues/56)  I inserted the its-term-info-ref attribute during the html round-tripping if in the nif file there is the itsrdf:termInfoRef  property.
In this case we decided to insert the Subject URI as the value of the attribute.
So for instance:
Dissident Chinese &lt;span its-term-info-ref="http://freme-project.eu/#char=1,7" its-term="yes">artist&lt;/span>. 
So should internationalization change the value of the attribute its-term-info-ref?
And which value to insert specifically?

**Comment by katia-vistatec** [comment]
[issue55.txt](https://github.com/freme-project/CKEditor-Plugin/files/563846/issue55.txt)
[issue55-ttl-out.txt](https://github.com/freme-project/CKEditor-Plugin/files/563847/issue55-ttl-out.txt)

**Comment by bjdmeest** [comment]
I'll let other people resolve https://github.com/freme-project/CKEditor-Plugin/issues/29#issuecomment-257541818 , but 17d38cb2b8a3750550400a91cf001657ad0712d2 solves https://github.com/freme-project/CKEditor-Plugin/issues/29#issuecomment-257401551 .

Some remarks:
* I change `<a>` to `<span>`, it didn't make sense to me to have a `a` without `href`
* If there are multiple term references, I add the first reference to `its-term-info-ref`, and add all references (including the first one) to `data-its-term-info-refs`
* The HTML might get very bloated with all the term references (some terms have 10+ references)

**Comment by fsasaki** [comment]
great, thanks! You are right about the size of the term references. Since AFAIk there is no weight of term references, it is hard to choose one as the canonical one. At least an application has them available.

**Comment by Katsivelisp** [comment]
Hello,

> I change \<a\> to \<span\>, it didn't make sense to me to have a a without href

just to add that from some examples of ours, it makes sense to have an href attribute. For example, when e-Terminology is invoked for agriculture-related texts, _its-term-info-ref_ elements also include AGROVOC URIs, which we mostly prefer over other term references (Tilde URLs). Same goes for our custom collections that we build on the Tilde Terminology website. 

So, I don't know if there should be a template or an option for terms to be marked as <a> or <span> elements. I think the code is fairly straight-forward anyway and we can edit it easily.

**Comment by philinthecloud** [comment]
Per meeting between Phil, Felix, Katia and Marta at Dublin face to face, we agree it should be the term identifier which is written to its-term-info-ref attribute.

**Comment by fsasaki** [comment]
attaching some examples: input, current output, expected output.
[example-expected-output.txt](https://github.com/freme-project/CKEditor-Plugin/files/594535/example-expected-output.txt)
[example-input.txt](https://github.com/freme-project/CKEditor-Plugin/files/594534/example-input.txt)
[example-output-turtle.txt](https://github.com/freme-project/CKEditor-Plugin/files/594536/example-output-turtle.txt)

**Comment by katia-vistatec** [comment]
Hi. For the example-input.txt file and the curl requests in curlRequests.txt file, I get the output in the attached files example-output20-dev.txt and example-output21-dev.txt.
[example-output20-dev.txt](https://github.com/freme-project/CKEditor-Plugin/files/597354/example-output20-dev.txt)
[example-output21-dev.txt](https://github.com/freme-project/CKEditor-Plugin/files/597355/example-output21-dev.txt)
[curlRequests.txt](https://github.com/freme-project/CKEditor-Plugin/files/597356/curlRequests.txt)

**Comment by fsasaki** [comment]
Hi Katia, thanks, it looks correct to me.

**Comment by pheyvaer** [comment]
@fsasaki can we close this?

**Comment by fsasaki** [comment]
Yes

2017-01-18 13:43 GMT+01:00 Pieter Heyvaert <notifications@github.com>:
